### ISSUE TITLE
the pix2pix.py showing attribute error

### ISSUE THREAD

**Issue by shah-jimish** [acvictor/Obama-Lip-Sync#10]
Traceback (most recent call last):
  File "pix2pix.py", line 805, in <module>
    main()
  File "pix2pix.py", line 627, in main
    examples = load_examples()
  File "pix2pix.py", line 261, in load_examples
    reader = tf.WholeFileReader()
AttributeError: module 'tensorflow' has no attribute 'WholeFileReader'

**Comment by acvictor** [comment]
This is probably a tensorflow version mismatch. 
https://www.tensorflow.org/api_docs/python/tf/compat/v1/WholeFileReader
