### ISSUE TITLE
h5 file

### ISSUE THREAD

**Issue by Sinshi** [acvictor/Obama-Lip-Sync#7]
When I run the run.py I'm getting this error
The syntax of the command is incorrect.
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    model = load_model(modelFile)
  File "C:\Users\hp-user\Anaconda3\envs\tensorflow_env\lib\site-packages\keras\engine\saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "C:\Users\hp-user\Anaconda3\envs\tensorflow_env\lib\site-packages\keras\utils\io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\hp-user\Anaconda3\envs\tensorflow_env\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\hp-user\Anaconda3\envs\tensorflow_env\lib\site-packages\h5py\_hl\files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'path/obama.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by eliranmoyal** [comment]
you need to download it from the models (and also some other files)
there are links here:
https://github.com/acvictor/Obama-Lip-Sync/tree/master/data
